import { cookieStorage, createStorage } from "wagmi";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { base, baseSepolia } from "@reown/appkit/networks";
import type { AppKitNetwork } from "@reown/appkit/networks";

// Read Project ID from environment variables
// TODO: Get your project ID from https://cloud.reown.com
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error(
    "NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local"
  );
}

// TODO: Set NEXT_PUBLIC_CHAIN_ID in your .env.local file
// Base Mainnet = 8453, Base Sepolia = 84532
const chainId = Number(process.env.NEXT_PUBLIC_CHAIN_ID || "84532");
const isMainnet = chainId === 8453;

// Define supported networks
export const networks: [AppKitNetwork, ...AppKitNetwork[]] = isMainnet
  ? [base]
  : [baseSepolia];

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;

